### ISSUE TITLE
snapshot alternative?

### ISSUE THREAD

**Issue by skywinder** [indisee/ITCiosScreenShotUploader#1]
Is there any issues with https://github.com/fastlane/snapshot that you decide to biuld your own?

**Comment by indisee** [comment]
**snapshot** is tool for **taking screenshots**
**deliver** is **command line** tool to upload screenshots
**ITCiosScreenShotUploader** is tool with UI for uploading screenshots, basically it's — drag&drop screenshots in window and press upload

**Comment by indisee** [comment]
and answering your question — i didn't use **fastlane** because i need UI tool and i don't know if there's some issues in it
